#!/bin/bash
#SBATCH -N 1
#SBATCH --partition=batch
#SBATCH -J zRGCN_ATTN
#SBATCH -o zRGCN_ATTN.%J.out
#SBATCH -e zRGCN_ATTN.%J.err
#SBATCH --mail-user=fernando.zhapacamacho@kaust.edu.sa
#SBATCH --mail-type=ALL
#SBATCH --time=10:00:00
#SBATCH --mem=64G
#SBATCH --gres=gpu:4
#SBATCH --constraint=[gpu]

#run the application:

module load gcc/6.4.0

python rgcn_lp_attn.py