#!/bin/bash
#SBATCH -N 1
#SBATCH --partition=batch
#SBATCH -J zRGCN
#SBATCH -o zRGCN.%J.out
#SBATCH -e zRGCN.%J.err
#SBATCH --mail-user=fernando.zhapacamacho@kaust.edu.sa
#SBATCH --mail-type=ALL
#SBATCH --time=10:00:00
#SBATCH --mem=64G
#SBATCH --gres=gpu:4
#SBATCH --constraint=[gpu]

#run the application:
module load gcc/6.4.0

python rgcn_lp.py